--[[
AdiBags_Archaeology - Adds Archaeology items to AdiBags virtual groups
Copyright © 2022 Paul Vandersypen, All Rights Reserved
]]--

local _, addon = ...
local L = addon.L

local db = {}

db.Filters = {
    ["archaeology"] = {
        uiName = PROFESSIONS_ARCHAEOLOGY,
        uiDesc = L["Archaeology Items"],
        title = PROFESSIONS_ARCHAEOLOGY,
        items = {
            -- itemID                   -- item name
            [51926]     = true,         -- Pristine Akun'Jar Vase
            [51929]     = true,         -- Pristine Urn of Passage
            [51932]     = true,         -- Pristine Rezan Idol
            [51934]     = true,         -- Pristine High Apothecary's Hood
            [51936]     = true,         -- Pristine Bwonsamdi Voodoo Mask
            [51937]     = true,         -- Pristine Blowgun of the Sethrak
            [51951]     = true,         -- Pristine Ancient Runebound Tome
            [51952]     = true,         -- Pristine Disembowling Sickle
            [51953]     = true,         -- Pristine Jagged Blade of the Drust
            [51954]     = true,         -- Pristine Ritual Fetish
            [51955]     = true,         -- Pristine Soul Coffer
            [52834]     = true,         -- Dwarf Rune Stone (key stone)
            [63127]     = true,         -- Highborne Scroll (key stone)
            [63128]     = true,         -- Troll Tablet (key stone)
            [64392]     = true,         -- Orc Blood Text (key stone)
            [64394]     = true,         -- Draenei Tome (key stone)
            [64395]     = true,         -- Vrykul Rune Stick (key stone)
            [64396]     = true,         -- Nerubian Obelisk (key stone)
            [64397]     = true,         -- Tol'vir Hieroglyphic (key stone)
            [79868]     = true,         -- Pandaren Pottery Shard (key stone)
            [79869]     = true,         -- Mogu Statue Piece (key stone)
            [87399]     = true,         -- Restored Artifact
            [87533]     = true,         -- Crate of Dwarf Archaeology Fragments
            [87534]     = true,         -- Crate of Draenei Archaeology Fragments
            [87535]     = true,         -- Crate of Fossil Archaeology Fragments
            [87536]     = true,         -- Crate of Night Elf Archaeology Fragments
            [87537]     = true,         -- Crate of Nerubian Archaeology Fragments
            [87538]     = true,         -- Crate of Orc Archaeology Fragments
            [87539]     = true,         -- Crate of Tol'vir Archaeology Fragments
            [87540]     = true,         -- Crate of Troll Archaeology Fragments
            [87541]     = true,         -- Crate of Vrykul Archaeology Fragments
            [87548]     = true,         -- Lorewalker's Lodestone
            [87549]     = true,         -- Lorewalker's Map
            [89169]     = true,         -- Pristine Manacles of Rebellion
            [95373]     = true,         -- Mantid Amber Sliver (key stone)
            [95383]     = true,         -- Pristine Banner of the Mantid Empire
            [95384]     = true,         -- Pristine Ancient Sap Feeder
            [95385]     = true,         -- Pristine Praying Mantid
            [95386]     = true,         -- Pristine Sound Beacon
            [95387]     = true,         -- Pristine Remains of a Paragon
            [95388]     = true,         -- Pristine Mantid Lamp
            [95389]     = true,         -- Pristine Pollen Collector
            [95390]     = true,         -- Pristine Kypari Sap Container
            [104198]    = true,         -- Mantid Artifact Hunter's Kit
            [108439]    = true,         -- Draenor Clan Orator Cane (key stone)
            [109584]    = true,         -- Ogre Missive (key stone)
            [109585]    = true,         -- Arakkoa Cipher (key stone)
            [109586]    = true,         -- Brittle Cartography Journal (WoD)
            [114142]    = true,         -- Pristine Fang-Scarred Frostwolf Axe
            [114144]    = true,         -- Pristine Frostwolf Ancestry Scrimshaw
            [114146]    = true,         -- Pristine Wolfskin Snowshoes
            [114148]    = true,         -- Pristine Warsinger's Drums
            [114150]    = true,         -- Pristine Screaming Bullroarer
            [114152]    = true,         -- Pristine Warsong Ceremonial Pike
            [114154]    = true,         -- Pristine Metalworker's Hammer
            [114156]    = true,         -- Pristine Elemental Bellows
            [114158]    = true,         -- Pristine Blackrock Razor
            [114160]    = true,         -- Pristine Weighted Chopping Axe
            [114162]    = true,         -- Pristine Hooked Dagger
            [114164]    = true,         -- Pristine Barbed Fishing Hook
            [114166]    = true,         -- Pristine Calcified Eye In a Jar
            [114168]    = true,         -- Pristine Ceremonial Tattoo Needles
            [114170]    = true,         -- Pristine Cracked Ivory Idol
            [114172]    = true,         -- Pristine Ancestral Talisman
            [114174]    = true,         -- Pristine Flask of Blazegrease
            [114176]    = true,         -- Pristine Gronn-Tooth Necklace
            [114178]    = true,         -- Pristine Doomsday Prophecy
            [114180]    = true,         -- Pristine Headdress of the First Shaman
            [114182]    = true,         -- Pristine Stonemaul Succession Stone
            [114184]    = true,         -- Pristine Stone Manacles
            [114186]    = true,         -- Pristine Ogre Figurine
            [114188]    = true,         -- Pristine Pictogram Carving
            [114208]    = true,         -- Pristine Gladiator's Shield
            [114209]    = true,         -- Pristine Mortar and Pestle
            [114210]    = true,         -- Pristine Eye of Har'gunn the Blind
            [114211]    = true,         -- Pristine Stone Dentures
            [114212]    = true,         -- Pristine Rylak Riding Harness
            [114213]    = true,         -- Pristine Imperial Decree Stele
            [114214]    = true,         -- Pristine Sorcerer-King Toe Ring
            [114215]    = true,         -- Pristine Dreamcatcher
            [114216]    = true,         -- Pristine Burial Urn
            [114217]    = true,         -- Pristine Decree Scrolls
            [114218]    = true,         -- Pristine Solar Orb
            [114219]    = true,         -- Pristine SUndial
            [114220]    = true,         -- Pristine Talonpriest Mask
            [114221]    = true,         -- Pristine Outcast Dreamcatcher
            [114222]    = true,         -- Pristine Apexis Crystal
            [114223]    = true,         -- Pristine Apexis Hieroglyph
            [114224]    = true,         -- Pristine Apexis Scroll
            [117386]    = true,         -- Crate of Pandaren Archaeology Fragments
            [117387]    = true,         -- Crate of Mogu Archaeology Fragments
            [117388]    = true,         -- Crate of Mantid Archaeology Fragments
            [117389]    = true,         -- Draenor Achaeologist's Lodestone
            [117390]    = true,         -- Draenor Archaeologist's Map
            [118728]    = true,         -- Shadowmoon Valley Treasure Map
            [118729]    = true,         -- Gorgrond Treasure Map
            [118730]    = true,         -- Talador Treasure Map
            [118731]    = true,         -- Spires of Arak Treasure Map
            [118732]    = true,         -- Nagrand Treasure Map
            [122606]    = true,         -- Explorer's Notebook
            [130903]    = true,         -- Ancient Suramar Scroll (key stone)
            [130904]    = true,         -- Highmountain Ritual-Stone (key stone)
            [130905]    = true,         -- Mark of the Deceiver (key stone)
            [130921]    = true,         -- Pristine Violetglass Vessel
            [130922]    = true,         -- Pristine Inert Leystone Charm
            [130923]    = true,         -- Pristine Quietwine Vial
            [130924]    = true,         -- Pristine Pre-War Highborne Tapestry
            [130925]    = true,         -- Pristine Nobleman's Letter Opener
            [130926]    = true,         -- Pristine Trailhead Drum
            [130927]    = true,         -- Pristine Moosebone Fish-Hook
            [130928]    = true,         -- Pristine Hand-Smoothed Pyrestone
            [130929]    = true,         -- Pristine Drogbar Gem-Roller
            [130930]    = true,         -- Pristine Stonewood Bow
            [130931]    = true,         -- Pristine Imp's Cup
            [130932]    = true,         -- Pristine Flayed-Skin Chronicle
            [130933]    = true,         -- Pristine Malformed Abyssal
            [130934]    = true,         -- Pristine Orb of Inner Chaos
            [130935]    = true,         -- Pristine Houndstooth Hauberk
            [134086]    = true,         -- Surveying Equipment
            [135488]    = true,         -- Goblin Explosives
            [136372]    = true,         -- Archaeologist's Whistle
            [136632]    = true,         -- Ancient War Remnants
            [136383]    = true,         -- Ravencrest Cache
            [136419]    = true,         -- Excavator's Notebook (Legion)
            [142113]    = true,         -- Crate of Arakkoa Archaeology Fragments
            [142114]    = true,         -- Crate of Draenor Clans Archaeology Fragments
            [142115]    = true,         -- Crate of Ogre Archaeology Fragments
            [154926]    = true,         -- Pristine Ceremonial Bonesaw
            [154989]    = true,         -- Zandalari Idol (key stone)
            [154990]    = true,         -- Etched Drust Bone (key stone)
            [164625]    = true,         -- Crate of Demon Archaeology Fragments
            [164626]    = true,         -- Crate of Highborne Archaeology Fragments
            [164627]    = true,         -- Crate of Highmountain Tauren Archaeology Fragments
            [183384]    = true,         -- Crate of Drust Archaeology Fragments
            [183385]    = true,         -- Crate of Zandalari Archaeology Fragments
        }
    }
}

-- return data to main file
addon.db = db